// Generated by tools/generate_interfaces.py. See pinned header provenance.
#pragma once
#include "trace.hpp"
#include <atomic>
#include <unordered_map>
namespace gfx2 {
class Device8;
class Root8 final : public IDirect3D8 {
public:
 explicit Root8(IDirect3D8* p) : real_(p) {}
 IDirect3D8* real() const noexcept { return real_; }
 void adopt() noexcept { ++refs_; }
 std::recursive_mutex registry_mutex;
 std::unordered_map<IDirect3DDevice8*,Device8*> devices;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) override;
 __declspec(noinline) ULONG STDMETHODCALLTYPE AddRef() override;
 __declspec(noinline) ULONG STDMETHODCALLTYPE Release() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE RegisterSoftwareDevice(void * pInitializeFunction) override;
 __declspec(noinline) UINT STDMETHODCALLTYPE GetAdapterCount() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetAdapterIdentifier(UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 * pIdentifier) override;
 __declspec(noinline) UINT STDMETHODCALLTYPE GetAdapterModeCount(UINT Adapter) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE EnumAdapterModes(UINT Adapter, UINT Mode, D3DDISPLAYMODE * pMode) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetAdapterDisplayMode(UINT Adapter, D3DDISPLAYMODE * pMode) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CheckDeviceType(UINT Adapter, D3DDEVTYPE CheckType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL Windowed) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CheckDeviceFormat(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CheckDeviceMultiSampleType(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CheckDepthStencilMatch(UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetDeviceCaps(UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS8 * pCaps) override;
 __declspec(noinline) HMONITOR STDMETHODCALLTYPE GetAdapterMonitor(UINT Adapter) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateDevice(UINT Adapter, D3DDEVTYPE DeviceType,HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS * pPresentationParameters, struct IDirect3DDevice8 ** ppReturnedDeviceInterface) override;
private: IDirect3D8* real_; std::atomic<ULONG> refs_{1};
};
class Device8 final : public IDirect3DDevice8 {
public:
 Device8(IDirect3DDevice8* p, Root8* parent) noexcept;
 ~Device8();
 void adopt() noexcept { ++refs_; }
 Trace trace;
 VisualPolicy visuals;
 HRESULT stock_for_unmapped(const char* reason) noexcept;
 HRESULT repair_reflection() noexcept;
 HRESULT draw_indexed_at(D3DPRIMITIVETYPE type,UINT min_index,UINT vertices,UINT start,UINT count,uintptr_t pc);
 __declspec(noinline) HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) override;
 __declspec(noinline) ULONG STDMETHODCALLTYPE AddRef() override;
 __declspec(noinline) ULONG STDMETHODCALLTYPE Release() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE TestCooperativeLevel() override;
 __declspec(noinline) UINT STDMETHODCALLTYPE GetAvailableTextureMem() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE ResourceManagerDiscardBytes(DWORD Bytes) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetDirect3D(IDirect3D8 ** ppD3D8) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetDeviceCaps(D3DCAPS8 * pCaps) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetDisplayMode(D3DDISPLAYMODE * pMode) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetCreationParameters(D3DDEVICE_CREATION_PARAMETERS * pParameters) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetCursorProperties(UINT XHotSpot, UINT YHotSpot, IDirect3DSurface8 * pCursorBitmap) override;
 __declspec(noinline) void STDMETHODCALLTYPE SetCursorPosition(UINT XScreenSpace, UINT YScreenSpace,DWORD Flags) override;
 __declspec(noinline) WINBOOL STDMETHODCALLTYPE ShowCursor(WINBOOL bShow) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateAdditionalSwapChain(D3DPRESENT_PARAMETERS * pPresentationParameters, IDirect3DSwapChain8 ** pSwapChain) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE Reset(D3DPRESENT_PARAMETERS * pPresentationParameters) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE Present(const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetBackBuffer(UINT BackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface8 ** ppBackBuffer) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetRasterStatus(D3DRASTER_STATUS * pRasterStatus) override;
 __declspec(noinline) void STDMETHODCALLTYPE SetGammaRamp(DWORD flags, const D3DGAMMARAMP *ramp) override;
 __declspec(noinline) void STDMETHODCALLTYPE GetGammaRamp(D3DGAMMARAMP * pRamp) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateTexture(UINT Width,UINT Height,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DTexture8 ** ppTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateVolumeTexture(UINT Width,UINT Height,UINT Depth,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DVolumeTexture8 ** ppVolumeTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateCubeTexture(UINT EdgeLength,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DCubeTexture8 ** ppCubeTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateVertexBuffer(UINT Length,DWORD Usage,DWORD FVF,D3DPOOL Pool,IDirect3DVertexBuffer8 ** ppVertexBuffer) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateIndexBuffer(UINT Length,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DIndexBuffer8 ** ppIndexBuffer) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateRenderTarget(UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,WINBOOL Lockable,IDirect3DSurface8 ** ppSurface) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateDepthStencilSurface(UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,IDirect3DSurface8 ** ppSurface) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateImageSurface(UINT Width,UINT Height,D3DFORMAT Format,IDirect3DSurface8 ** ppSurface) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CopyRects(IDirect3DSurface8 *src_surface, const RECT *src_rects, UINT rect_count, IDirect3DSurface8 *dst_surface, const POINT *dst_points) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE UpdateTexture(IDirect3DBaseTexture8 * pSourceTexture,IDirect3DBaseTexture8 * pDestinationTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetFrontBuffer(IDirect3DSurface8 * pDestSurface) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetRenderTarget(IDirect3DSurface8 * pRenderTarget,IDirect3DSurface8 * pNewZStencil) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetRenderTarget(IDirect3DSurface8 ** ppRenderTarget) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetDepthStencilSurface(IDirect3DSurface8 ** ppZStencilSurface) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE BeginScene() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE EndScene() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE Clear(DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE State,D3DMATRIX * pMatrix) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetViewport(const D3DVIEWPORT8 *viewport) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetViewport(D3DVIEWPORT8 * pViewport) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetMaterial(const D3DMATERIAL8 *material) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetMaterial(D3DMATERIAL8 *pMaterial) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetLight(DWORD index, const D3DLIGHT8 *light) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetLight(DWORD Index,D3DLIGHT8 * pLight) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE LightEnable(DWORD Index,WINBOOL Enable) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetLightEnable(DWORD Index,WINBOOL * pEnable) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetClipPlane(DWORD index, const float *plane) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetClipPlane(DWORD Index,float * pPlane) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE State,DWORD Value) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE State,DWORD * pValue) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE BeginStateBlock() override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE EndStateBlock(DWORD * pToken) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE ApplyStateBlock(DWORD Token) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CaptureStateBlock(DWORD Token) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DeleteStateBlock(DWORD Token) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateStateBlock(D3DSTATEBLOCKTYPE Type,DWORD * pToken) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetClipStatus(const D3DCLIPSTATUS8 *clip_status) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetClipStatus(D3DCLIPSTATUS8 * pClipStatus) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetTexture(DWORD Stage,IDirect3DBaseTexture8 ** ppTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetTexture(DWORD Stage,IDirect3DBaseTexture8 * pTexture) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD * pValue) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD Value) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE ValidateDevice(DWORD * pNumPasses) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetInfo(DWORD DevInfoID,void * pDevInfoStruct,DWORD DevInfoStructSize) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetPaletteEntries(UINT palette_idx, const PALETTEENTRY *entries) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetPaletteEntries(UINT PaletteNumber,PALETTEENTRY * pEntries) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetCurrentTexturePalette(UINT PaletteNumber) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetCurrentTexturePalette(UINT * PaletteNumber) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType,UINT StartVertex,UINT PrimitiveCount) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE PrimitiveType,UINT minIndex,UINT NumVertices,UINT startIndex,UINT primCount) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE ProcessVertices(UINT SrcStartIndex,UINT DestIndex,UINT VertexCount,IDirect3DVertexBuffer8 * pDestBuffer,DWORD Flags) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreateVertexShader(const DWORD *declaration, const DWORD *byte_code, DWORD *shader, DWORD usage) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetVertexShader(DWORD Handle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetVertexShader(DWORD * pHandle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DeleteVertexShader(DWORD Handle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetVertexShaderConstant(DWORD reg_idx, const void *data, DWORD count) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetVertexShaderConstant(DWORD Register,void * pConstantData,DWORD ConstantCount) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetVertexShaderDeclaration(DWORD Handle,void * pData,DWORD * pSizeOfData) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetVertexShaderFunction(DWORD Handle,void * pData,DWORD * pSizeOfData) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetStreamSource(UINT StreamNumber,IDirect3DVertexBuffer8 * pStreamData,UINT Stride) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetStreamSource(UINT StreamNumber,IDirect3DVertexBuffer8 ** ppStreamData,UINT * pStride) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetIndices(IDirect3DIndexBuffer8 * pIndexData,UINT BaseVertexIndex) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetIndices(IDirect3DIndexBuffer8 ** ppIndexData,UINT * pBaseVertexIndex) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE CreatePixelShader(const DWORD *byte_code, DWORD *shader) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetPixelShader(DWORD Handle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetPixelShader(DWORD * pHandle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DeletePixelShader(DWORD Handle) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE SetPixelShaderConstant(DWORD reg_idx, const void *data, DWORD count) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetPixelShaderConstant(DWORD Register,void * pConstantData,DWORD ConstantCount) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE GetPixelShaderFunction(DWORD Handle,void * pData,DWORD * pSizeOfData) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawRectPatch(UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DrawTriPatch(UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info) override;
 __declspec(noinline) HRESULT STDMETHODCALLTYPE DeletePatch(UINT Handle) override;
private: IDirect3DDevice8* real_; Root8* parent_; std::atomic<ULONG> refs_{1};
};
}
