"""Master Rallye clean-room asset extraction research library."""
from .dx import parse_dx, parse_dx_bytes
from .dxt import (
    decode_rgba_pixels,
    encode_dxt_pixels,
    parse_dxt,
    parse_dxt_bytes,
    replace_dxt_pixels,
)
from .dx_writer import audit_binary_diff, patch_dx_positions, write_dx_positions
from .collision import parse_collision_sections
from .collision_writer import (
    patch_dx_collision_translation,
    replace_dx_tag101,
    serialize_tag101,
    translate_tag101,
    write_dx_collision_translation,
)
from .bounds import DxSpatialBounds1339, parse_bounds1339, compute_bounds1339
from .collision_scale import scale_tag101, scale_dx_collision
from .vehicle_project import VehicleProject, validate_vehicle, build_vehicle_mod
from .course_sdk import (
    CourseSourceMesh,
    CourseDependencies,
    CourseDependency,
    CourseFinishArea,
    CourseMarkerArea,
    CourseProject,
    CourseRaceLogic,
    CourseRenderDraw,
    CourseRenderGroup,
    CourseRenderResource,
    CourseResourcePaths,
    CourseSpatialField,
    CourseSplitTime,
    CourseStartArea,
    CourseTag100Region,
    CourseVisualCheckpoint,
    build_course_race_logic,
    discover_course_resources,
    load_course_project,
)
from .dx_course import parse_course_dx, parse_course_dx_bytes
from .course_xml import parse_course_xml, parse_course_xml_bytes
from .course_gxm import (
    CourseGxmBank,
    CourseGxmModelV7,
    CourseGxmTriangleV7,
    CourseGxmV7Validation,
    parse_course_gxm,
    parse_course_gxm_bytes,
    parse_course_gxm_model_v7,
    parse_course_gxm_model_v7_bytes,
)
from .course_source import parse_course_txt, parse_course_txt_bytes
from .course_spatial import (
    acute_xz_angle_degrees,
    analyze_source_mesh,
    bounds3,
    centroid3,
    gxm_source_to_runtime,
    pair_to_marker_polygon,
    point_to_segment_distance_xz,
    point_to_marker_polygon,
    runtime_to_blender,
    source_model_position_owners,
)
from .hnt import parse_hnt, parse_hnt_bytes
from .sfl import parse_sfl, parse_sfl_bytes
from .authoring import (
    INVALID_PROVENANCE,
    POSITIONS_ONLY_CHANGED,
    SOURCE_IDENTICAL,
    UNSUPPORTED_TOPOLOGY_CHANGED,
    provenance_fingerprint,
    validate_authoring_state,
)
from .errors import BoundsError, CollisionWriteError, DxWriteError, ExportError, FormatError, MasterRallyeError, UnknownRecordTagError
from .sidecar import parse_sidecar, resolve_sidecar

__all__ = [
    "BoundsError",
    "ExportError",
    "DxWriteError",
    "CollisionWriteError",
    "FormatError",
    "MasterRallyeError",
    "UnknownRecordTagError",
    "DxSpatialBounds1339",
    "parse_bounds1339",
    "compute_bounds1339",
    "scale_tag101",
    "scale_dx_collision",
    "VehicleProject",
    "CourseProject",
    "CourseSourceMesh",
    "CourseRaceLogic",
    "CourseStartArea",
    "CourseFinishArea",
    "CourseMarkerArea",
    "CourseSplitTime",
    "CourseVisualCheckpoint",
    "CourseRenderResource",
    "CourseRenderDraw",
    "CourseRenderGroup",
    "CourseResourcePaths",
    "CourseTag100Region",
    "CourseDependencies",
    "CourseDependency",
    "CourseSpatialField",
    "build_course_race_logic",
    "discover_course_resources",
    "load_course_project",
    "parse_course_dx",
    "parse_course_dx_bytes",
    "parse_course_xml",
    "parse_course_xml_bytes",
    "parse_course_gxm",
    "parse_course_gxm_bytes",
    "parse_course_gxm_model_v7",
    "parse_course_gxm_model_v7_bytes",
    "CourseGxmBank",
    "CourseGxmModelV7",
    "CourseGxmTriangleV7",
    "CourseGxmV7Validation",
    "parse_course_txt",
    "parse_course_txt_bytes",
    "gxm_source_to_runtime",
    "runtime_to_blender",
    "centroid3",
    "bounds3",
    "point_to_segment_distance_xz",
    "acute_xz_angle_degrees",
    "analyze_source_mesh",
    "pair_to_marker_polygon",
    "point_to_marker_polygon",
    "source_model_position_owners",
    "parse_hnt",
    "parse_hnt_bytes",
    "parse_sfl",
    "parse_sfl_bytes",
    "validate_vehicle",
    "build_vehicle_mod",
    "parse_dx",
    "parse_dx_bytes",
    "patch_dx_positions",
    "write_dx_positions",
    "audit_binary_diff",
    "parse_collision_sections",
    "serialize_tag101",
    "replace_dx_tag101",
    "translate_tag101",
    "patch_dx_collision_translation",
    "write_dx_collision_translation",
    "SOURCE_IDENTICAL",
    "POSITIONS_ONLY_CHANGED",
    "UNSUPPORTED_TOPOLOGY_CHANGED",
    "INVALID_PROVENANCE",
    "provenance_fingerprint",
    "validate_authoring_state",
    "parse_dxt",
    "parse_dxt_bytes",
    "decode_rgba_pixels",
    "encode_dxt_pixels",
    "replace_dxt_pixels",
    "parse_sidecar",
    "resolve_sidecar",
]
