"""Generate complete override declarations/forwarders from the pinned SDK header.

Only writes inside the R-GFX2 directory. Re-running is deterministic. No game input.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def interfaces(header):
    result = {}
    for interface in ('IDirect3D8', 'IDirect3DDevice8'):
        block = re.search(r'DECLARE_INTERFACE_IID_\('+interface+r',.*?\)\s*\{(.*?)\};', header, re.S).group(1)
        methods = []
        for match in re.finditer(r'STDMETHOD(?:_\((\w+)\s*,\s*(\w+)\s*\)|\((\w+)\))\s*\((.*?)\)\s*PURE;', block, re.S):
            ret, name, fallback, params = match.groups()
            name = name or fallback
            params = re.sub(r'\bTHIS_?\b', '', params).strip()
            params = ' '.join(params.split())
            args = [re.search(r'(\w+)\s*$', arg).group(1) for arg in params.split(',')] if params else []
            methods.append({'slot':len(methods),'method':name,'return_type':ret or 'HRESULT',
                'parameters':params,'arguments':args,'implemented_wrapper':True,
                'logging_category':'COM' if name in ('QueryInterface','AddRef','Release','GetDirect3D','CreateDevice') else 'observational' if interface.endswith('Device8') else 'forward_only',
                'forwarding_status':'unchanged except documented COM pointer plumbing'})
        result[interface] = methods
    for method in result['IDirect3D8']:
        if method['method']=='CreateDevice':
            method['forwarding_status']='default-off unchanged; COM pointer plumbing and R-GFX5 D3D-generic display/MSAA parameters with bounded native fallback'
    for method in result['IDirect3DDevice8']:
        if method['method'] in ('SetTextureStageState','SetTransform','GetTextureStageState','GetTransform','DrawPrimitive','DrawIndexedPrimitive','Reset','Present','SetViewport','GetViewport'):
            method['forwarding_status']='default-off unchanged; documented R-GFX3/R-GFX4/R-GFX5 gated override or logical getter virtualization'
        elif method['method'] in ('DrawPrimitiveUP','DrawIndexedPrimitiveUP'):
            method['forwarding_status']='unchanged except fail-closed repair after a reported native reflection or UI WORLD restore failure'
        elif method['method'] in ('BeginStateBlock','ApplyStateBlock','CreateStateBlock','CaptureStateBlock','MultiplyTransform'):
            method['forwarding_status']='default-off unchanged; active visual state restored before unreviewed operation'
    if [len(result[x]) for x in result] != [16,97]:
        raise ValueError('Pinned header interface counts changed')
    return result

def generate():
    methods = interfaces((ROOT/'vendor/d3d8/d3d8.h').read_text())
    (ROOT/'data/interface-map.json').write_text(json.dumps({'schema_version':1,'source':'vendor/d3d8/d3d8.h','interfaces':methods},indent=2)+'\n',newline='\n')
    declarations = ['// Generated by tools/generate_interfaces.py. See pinned header provenance.',
        '#pragma once','#include "trace.hpp"','#include "game_fov.hpp"','#include "race_epoch.hpp"','#include "quality.hpp"','#include "ui_margins.hpp"','#include <array>','#include <atomic>','#include <memory>','#include <mutex>','#include <unordered_map>','#include <vector>',
        'namespace gfx2 {','class Device8;','class BufferProxyCore;','struct BufferMirror;','enum class BufferKind;',
        'class Root8 final : public IDirect3D8 {','public:',
        ' explicit Root8(IDirect3D8* p) : real_(p) {}',
        ' IDirect3D8* real() const noexcept { return real_; }',
        ' void adopt() noexcept { ++refs_; }',
        ' std::recursive_mutex registry_mutex;',
        ' std::unordered_map<IDirect3DDevice8*,Device8*> devices;']
    for m in methods['IDirect3D8']:
        declarations.append(f' __declspec(noinline) {m["return_type"]} STDMETHODCALLTYPE {m["method"]}({m["parameters"]}) override;')
    declarations += ['private: IDirect3D8* real_; std::atomic<ULONG> refs_{1};','};',
        'class Device8 final : public IDirect3DDevice8 {','public:',
        ' Device8(IDirect3DDevice8* p, Root8* parent, std::unique_ptr<QualityPipeline> quality = {}) noexcept;',
        ' ~Device8();',
        ' void adopt() noexcept { ++refs_; }',' IDirect3DDevice8* native() const noexcept { return real_; }',
        ' IDirect3DVertexBuffer8* wrap_vertex_buffer(IDirect3DVertexBuffer8* raw) noexcept;',' IDirect3DIndexBuffer8* wrap_index_buffer(IDirect3DIndexBuffer8* raw) noexcept;',
        ' IDirect3DVertexBuffer8* unwrap_vertex_buffer(IDirect3DVertexBuffer8* buffer) noexcept;',' IDirect3DIndexBuffer8* unwrap_index_buffer(IDirect3DIndexBuffer8* buffer) noexcept;',
        ' bool register_buffer_proxy(void* raw,BufferProxyCore* proxy) noexcept;',' void forget_buffer_proxy(void* raw,BufferProxyCore* proxy) noexcept;',
        ' std::shared_ptr<BufferMirror> open_buffer_mirror(void* raw,BufferKind kind,uint64_t generation,UINT bytes,DWORD usage,D3DPOOL pool) noexcept;',
        ' bool copy_buffer_shadow(void* raw,BufferKind kind,uint64_t generation,uint64_t offset,size_t size,std::vector<BYTE>& out,uint64_t& revision) noexcept;',
        ' void invalidate_buffer_shadow(void* raw,const char* reason) noexcept;',' void invalidate_all_buffer_shadows(const char* reason) noexcept;',
        ' void note_stream_buffer_binding(UINT stream,void* raw,HRESULT result) noexcept;',' void note_index_buffer_binding(void* raw,HRESULT result) noexcept;',
        ' bool reserve_buffer_copy_bytes(size_t bytes) noexcept;',
        ' Trace trace;',' std::unique_ptr<QualityPipeline> quality;',' HRESULT set_transform_at(D3DTRANSFORMSTATETYPE type,const D3DMATRIX* input,uintptr_t pc);',' UiMargins ui_margins;',' void quality_trace() noexcept;',' HRESULT stock_ui(const char* reason) noexcept;',' VisualPolicy visuals;',' GameFov game_fov;',' bool race_observer_attached=false;',' HRESULT stock_for_unmapped(const char* reason) noexcept;',' HRESULT repair_reflection() noexcept;',' HRESULT draw_primitive_at(D3DPRIMITIVETYPE type,UINT start,UINT count,uintptr_t pc);',' HRESULT draw_indexed_at(D3DPRIMITIVETYPE type,UINT min_index,UINT vertices,UINT start,UINT count,uintptr_t pc);']
    for m in methods['IDirect3DDevice8']:
        declarations.append(f' __declspec(noinline) {m["return_type"]} STDMETHODCALLTYPE {m["method"]}({m["parameters"]}) override;')
    declarations += ['private:',' IDirect3DDevice8* real_; Root8* parent_; std::atomic<ULONG> refs_{1};',
        ' std::recursive_mutex buffer_mutex_;',' std::unordered_map<void*,BufferProxyCore*> buffer_proxies_;',' std::unordered_map<void*,BufferProxyCore*> buffer_proxy_interfaces_;',
        ' std::unordered_map<void*,std::shared_ptr<BufferMirror>> buffer_mirrors_;',' std::array<void*,16> stream_buffers_{};',' void* index_buffer_=nullptr;',
        ' uint64_t buffer_shadow_bytes_=0,buffer_copy_frame_=0,buffer_copy_bytes_=0;',' void discard_unbound_buffer_mirror_locked(void* raw) noexcept;','};','}']
    (ROOT/'include/wrappers.hpp').write_text('\n'.join(declarations)+'\n',newline='\n')
    lines = ['// Generated complete forwarders; COM plumbing is in wrappers.cpp.', '#include "wrappers.hpp"','#include "provenance.hpp"','#include "buffer_provenance.hpp"','#include <intrin.h>','namespace gfx2 {']
    names = []
    for interface, owner in [('IDirect3D8','Root8'),('IDirect3DDevice8','Device8')]:
        for m in methods[interface]:
            ret,name,params,args = m['return_type'],m['method'],m['parameters'],', '.join(m['arguments'])
            if name in ('QueryInterface','AddRef','Release','CreateDevice','GetDirect3D') or owner=='Device8' and name in ('SetTextureStageState','GetTextureStageState','SetTransform','GetTransform','DrawPrimitive','DrawIndexedPrimitive','Reset','Present','SetViewport','GetViewport'):continue
            if owner=='Device8' and name in ('CreateVertexBuffer','CreateIndexBuffer','GetStreamSource','GetIndices','SetStreamSource','SetIndices','ProcessVertices'):
                lines.append(f'{ret} STDMETHODCALLTYPE {owner}::{name}({params}) {{')
                lines += [' auto guard = trace.guard();',f' const auto pc = reinterpret_cast<uintptr_t>(_ReturnAddress());']
                if name in ('CreateVertexBuffer','CreateIndexBuffer'):
                    lines += [f' const auto args = pack({args});',f' trace.before({m["slot"]}, args, pc);',f' HRESULT result = real_->{name}({args});',f' trace.after({m["slot"]}, args, static_cast<uint32_t>(result), pc);']
                    output='ppVertexBuffer' if name=='CreateVertexBuffer' else 'ppIndexBuffer'
                    interface_type='IDirect3DVertexBuffer8' if name=='CreateVertexBuffer' else 'IDirect3DIndexBuffer8'
                    wrap='wrap_vertex_buffer' if name=='CreateVertexBuffer' else 'wrap_index_buffer'
                    lines += [f' if(SUCCEEDED(result)&&visuals.effective.foliage_diagnostics&&{output}){{{interface_type}* raw=nullptr;if(safe_copy(&raw,{output},sizeof(raw))&&raw){{auto* wrapped={wrap}(raw);if(wrapped!=raw&&!safe_copy({output},&wrapped,sizeof(wrapped)))wrapped->Release();}}}}',' return result;']
                elif name in ('GetStreamSource','GetIndices'):
                    lines += [f' const auto args = pack({args});',f' trace.before({m["slot"]}, args, pc);',f' HRESULT result = real_->{name}({args});',f' trace.after({m["slot"]}, args, static_cast<uint32_t>(result), pc);']
                    output='ppStreamData' if name=='GetStreamSource' else 'ppIndexData'
                    interface_type='IDirect3DVertexBuffer8' if name=='GetStreamSource' else 'IDirect3DIndexBuffer8'
                    wrap='wrap_vertex_buffer' if name=='GetStreamSource' else 'wrap_index_buffer'
                    lines += [f' if(SUCCEEDED(result)&&visuals.effective.foliage_diagnostics&&{output}){{{interface_type}* raw=nullptr;if(safe_copy(&raw,{output},sizeof(raw))&&raw){{auto* wrapped={wrap}(raw);if(wrapped!=raw&&!safe_copy({output},&wrapped,sizeof(wrapped)))wrapped->Release();}}}}',' return result;']
                elif name in ('SetStreamSource','SetIndices'):
                    stream_name='StreamNumber' if name=='SetStreamSource' else None
                    buffer_name='pStreamData' if name=='SetStreamSource' else 'pIndexData'
                    unwrap='unwrap_vertex_buffer' if name=='SetStreamSource' else 'unwrap_index_buffer'
                    native_name='native_buffer'
                    lines += [f' auto* {native_name}={unwrap}({buffer_name});',f' const auto native_args = pack({args.replace(buffer_name, native_name)});',f' trace.before({m["slot"]}, native_args, pc);',f' HRESULT result = real_->{name}({args.replace(buffer_name, native_name)});']
                    if name=='SetStreamSource':lines.append(f' note_stream_buffer_binding({stream_name},{native_name},result);')
                    else:lines.append(f' note_index_buffer_binding({native_name},result);')
                    lines += [f' trace.after({m["slot"]}, native_args, static_cast<uint32_t>(result), pc);',' return result;']
                else: # ProcessVertices can write a destination buffer outside Lock/Unlock.
                    lines += [' auto* native_buffer=unwrap_vertex_buffer(pDestBuffer);',' const auto native_args=pack(SrcStartIndex,DestIndex,VertexCount,native_buffer,Flags);',f' trace.before({m["slot"]},native_args,pc);',' HRESULT result=real_->ProcessVertices(SrcStartIndex,DestIndex,VertexCount,native_buffer,Flags);',' if(SUCCEEDED(result)&&pDestBuffer)invalidate_buffer_shadow(native_buffer,"device_process_vertices_write");',f' trace.after({m["slot"]},native_args,static_cast<uint32_t>(result),pc);',' return result;']
                lines.append('}')
                continue
            lines.append(f'{ret} STDMETHODCALLTYPE {owner}::{name}({params}) {{')
            if owner == 'Root8':
                lines.append(f' {"return " if ret!="void" else ""}real_->{name}({args});')
            else:
                lines += [' auto guard = trace.guard();',f' const auto args = pack({args});',f' const auto pc = reinterpret_cast<uintptr_t>(_ReturnAddress());',f' trace.before({m["slot"]}, args, pc);',
                    *([' trace.culling=game_fov.status(); game_fov.finish_frame(); trace.culling.restored=game_fov.status().restored;'] if name=='Present' else [' game_fov.finish_frame();'] if name=='Reset' else []),
                    *([f' HRESULT safe = stock_for_unmapped("{name}");', ' if(FAILED(safe)){ trace.after('+str(m['slot'])+', args, static_cast<uint32_t>(safe), pc); return safe; }'] if name in ('BeginStateBlock','ApplyStateBlock','CreateStateBlock','CaptureStateBlock') else [f' if(state==D3DTS_PROJECTION){{HRESULT safe=stock_for_unmapped("MultiplyTransform_PROJECTION");if(FAILED(safe)){{trace.after({m["slot"]},args,static_cast<uint32_t>(safe),pc);return safe;}}}}'] if name=='MultiplyTransform' else []),
                    *([' HRESULT repair=repair_reflection();',f' if(FAILED(repair)){{trace.after({m["slot"]},args,static_cast<uint32_t>(repair),pc,nullptr,8,true);return repair;}}'] if name in ('DrawPrimitiveUP','DrawIndexedPrimitiveUP') else []),
                    f' {ret+" result = " if ret!="void" else ""}real_->{name}({args});',
                    *([' if(quality)quality->cooperative_result(result);'] if name=='TestCooperativeLevel' else []),
                    f' trace.after({m["slot"]}, args, {"static_cast<uint32_t>(result)" if ret!="void" else "0"}, pc);']
                if ret != 'void':lines.append(' return result;')
            lines.append('}')
    lines.append('}')
    (ROOT/'src/forwarders.cpp').write_text('\n'.join(lines)+'\n',newline='\n')
    names = [m['method'] for m in methods['IDirect3DDevice8']]
    (ROOT/'include/method_names.hpp').write_text('#pragma once\nnamespace gfx2 { inline constexpr const char* METHOD_NAMES[] = {\n'+',\n'.join(json.dumps(x) for x in names)+'\n}; }\n',newline='\n')
    mocks = ['// Generated ABI-wide mock methods and invocation tests.', '#pragma once', '#include "wrappers.hpp"', 'namespace gfx2 {']
    invokes = []
    for interface, owner in [('IDirect3D8','MockRootBase'),('IDirect3DDevice8','MockDeviceBase')]:
        mocks += [f'class {owner} : public {interface} {{', 'public:', ' uint32_t last=UINT32_MAX; Args observed{};', ' HRESULT hr=static_cast<HRESULT>(0x88761234u);']
        calls = []
        for m in methods[interface]:
            name, ret, params = m['method'], m['return_type'], m['parameters']
            body = f'last={m["slot"]};'
            if name != 'QueryInterface':body += 'observed=pack('+', '.join(m['arguments'])+');'
            body += 'return hr;' if ret == 'HRESULT' else 'return reinterpret_cast<HMONITOR>(0x12345678);' if ret == 'HMONITOR' else 'return 0x12345678;' if ret != 'void' else ''
            mocks.append(f' {ret} STDMETHODCALLTYPE {name}({params}) override {{ {body} }}')
            if name in ('QueryInterface','AddRef','Release','CreateDevice','GetDirect3D'):continue
            args=[]
            for i,param in enumerate(params.split(',') if params else []):
                typ=re.sub(r'\s*\b\w+\s*$', '', param).strip()
                args.append(f'reinterpret_cast<{typ}>(uintptr_t({0x1000+i*16}))' if '*' in typ or typ in ('HWND','HMONITOR') else f'static_cast<{typ}>({i+1})')
            call=f'w->{name}('+', '.join(args)+')'
            calls += [' { m.last=UINT32_MAX;',f' {"auto result = " if ret != "void" else ""}{call};',f' CHECK(m.last=={m["slot"]});',
                      ' CHECK(m.observed.a==pack('+', '.join(args)+').a);']
            if ret!='void':calls.append(' CHECK(result=='+('m.hr' if ret=='HRESULT' else 'reinterpret_cast<HMONITOR>(0x12345678)' if ret=='HMONITOR' else '0x12345678')+');')
            calls.append(' }')
        mocks.append('};')
        invokes += [f'inline void test_all_{owner}({interface}* w, {owner}& m) {{']+calls+['}']
    (ROOT/'tests/mock_interfaces.hpp').write_text('\n'.join(mocks+invokes+['}'])+'\n',newline='\n')

if __name__ == '__main__':
    generate()
