"""Read-only, hash-locked decoded recipes for native feature-local validation.

Only E8 rel32 CALL operands are normalized. Absolute globals and short control
flow remain exact (the documented freeze displacement admits 0x11 or 0x00).
Generated compact evidence is safe to commit; the input executable is not.
"""
import argparse
import hashlib
import json
from pathlib import Path
import capstone
import pefile

ROOT=Path(__file__).resolve().parents[1]
TARGET='bf8aef32407eb6552c05045b8abef149f32983cedd9503b865069b444c5f96b4'

def recipe(pe,start,end,target,anchor,freeze=False):
    code=pe.get_data(start,end-start)
    md=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32);md.detail=True
    rows=[];consumed=0
    for ins in md.disasm(code,pe.OPTIONAL_HEADER.ImageBase+start):
        relative=ins.mnemonic=='call' and ins.bytes[0]==0xe8 and ins.size==5
        prefix=[]
        if relative:
            dest=ins.operands[0].imm-pe.OPTIONAL_HEADER.ImageBase
            section=pe.get_section_by_rva(dest)
            if section is None or not section.Characteristics&0x20000000:raise ValueError('CALL target is not executable')
            prefix=list(pe.get_data(dest,12))
        rows.append(dict(offset=consumed,length=ins.size,relative_call=relative,callee_prefix=prefix,
                         instruction=ins.mnemonic+' '+ins.op_str))
        consumed+=ins.size
    if consumed!=len(code):raise ValueError('Incomplete instruction decode')
    return dict(known_rva=start,target_offset=target-start,anchor_size=anchor,
                freeze_branch=freeze,bytes=list(code),instructions=rows)

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('exe',type=Path);a=ap.parse_args()
    data=a.exe.read_bytes()
    if hashlib.sha256(data).hexdigest()!=TARGET:raise ValueError('Not the canonical pristine image')
    pe=pefile.PE(data=data)
    recipes={'MenuFreezeFix':recipe(pe,0x1b015a,0x1b0171,0x1b015c,12,True),
             'WidescreenUI':recipe(pe,0x161df0,0x161ed3,0x161ed3,11)}
    # Function boundaries independently exported from pristine Ghidra 12.1.4.
    owners={'CameraManager':(0xe3dd0,0xe3e32),'RendererHolder':(0x13eed0,0x13ef6b),
            'CameraAngle':(0xf2350,0xf237f),'ProjectionOwner':(0x1614a0,0x161a3f),
            'TransformOwner':(0x13f9e0,0x13fa7d),'FrameScheduler':(0x253080,0x253336),
            'SubmitOwner':(0x109680,0x1096d1),'SharedWorldOwner':(0x176970,0x177088),
            'UiPacketOwner':(0x16d110,0x16db10)}
    for name,(start,end) in owners.items():
        recipes[name]=recipe(pe,start,end,start,1);recipes[name]['fixed_rva']=True
    lines=['// Generated by tools/generate_fingerprints.py; decoded pristine instruction recipes.',
           '#pragma once','#include "compatibility.hpp"','namespace gfx2 {']
    for name,row in recipes.items():
        func='freeze_fingerprint' if name=='MenuFreezeFix' else 'ui_fingerprint' if name=='WidescreenUI' else 'owner_'+name
        lines += [f'FeatureFingerprint {func}() {{', ' FeatureFingerprint f;',
                  f' f.id="{name}";f.known_rva=0x{row["known_rva"]:x};f.target_offset={row["target_offset"]};f.anchor_size={row["anchor_size"]};f.freeze_branch={str(row["freeze_branch"]).lower()};',
                  ' f.fixed_rva='+str(row.get('fixed_rva',False)).lower()+';',
                  ' f.bytes={'+','.join(f'0x{x:02x}' for x in row['bytes'])+'};',' f.instructions={']
        for ins in row['instructions']:
            lines.append('  {'+f'{ins["offset"]},{ins["length"]},{str(ins["relative_call"]).lower()},'+'{'+','.join(f'0x{x:02x}' for x in ins['callee_prefix'])+'}},')
        lines += [' };return f;','}']
    for group,names in {'camera_owner_recipes':['CameraManager','RendererHolder','CameraAngle','ProjectionOwner','TransformOwner'],
                        'fov_owner_recipes':['CameraManager','RendererHolder','CameraAngle','ProjectionOwner','TransformOwner','FrameScheduler','SubmitOwner'],
                        'vehicle_owner_recipes':['CameraManager','RendererHolder','CameraAngle','ProjectionOwner','TransformOwner','SharedWorldOwner'],
                        'margin_owner_recipes':['UiPacketOwner']}.items():
        lines.append('std::vector<FeatureFingerprint> '+group+'() {return {'+','.join('owner_'+n+'()' for n in names)+'};}')
    lines+=['}']
    (ROOT/'include/fingerprint_recipes.hpp').write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
    metadata={'sha256':TARGET,'image_base':pe.OPTIONAL_HEADER.ImageBase,
              'normalization':'E8 rel32 only for scanned freeze/UI; fixed-layout owner groups match every byte including all operands',
              'source':'pristine Ghidra 12.1.4 read-only owner exports + Capstone full instruction decode'}
    text=json.dumps(metadata,indent=2)[:-2]+',\n  "features": {\n'
    parts=[]
    for name,row in recipes.items():
        fields=[]
        for key,value in row.items():
            if key=='instructions':
                value_text='[\n'+',\n'.join('        '+json.dumps(ins) for ins in value)+'\n      ]'
            else:value_text=json.dumps(value)
            fields.append('      '+json.dumps(key)+': '+value_text)
        parts.append('    '+json.dumps(name)+': {\n'+',\n'.join(fields)+'\n    }')
    text+=',\n'.join(parts)+'\n  }\n}\n'
    (ROOT/'research/r-gfx5/fingerprint-recipes.json').write_text(text,encoding='utf-8',newline='\n')


if __name__=='__main__':main()
