"""Generate complete override declarations/forwarders from the pinned SDK header.

Only writes inside the R-GFX2 directory. Re-running is deterministic. No game input.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def interfaces(header):
    result = {}
    for interface in ('IDirect3D8', 'IDirect3DDevice8'):
        block = re.search(r'DECLARE_INTERFACE_IID_\('+interface+r',.*?\)\s*\{(.*?)\};', header, re.S).group(1)
        methods = []
        for match in re.finditer(r'STDMETHOD(?:_\((\w+)\s*,\s*(\w+)\s*\)|\((\w+)\))\s*\((.*?)\)\s*PURE;', block, re.S):
            ret, name, fallback, params = match.groups()
            name = name or fallback
            params = re.sub(r'\bTHIS_?\b', '', params).strip()
            params = ' '.join(params.split())
            args = [re.search(r'(\w+)\s*$', arg).group(1) for arg in params.split(',')] if params else []
            methods.append({'slot':len(methods),'method':name,'return_type':ret or 'HRESULT',
                'parameters':params,'arguments':args,'implemented_wrapper':True,
                'logging_category':'COM' if name in ('QueryInterface','AddRef','Release','GetDirect3D','CreateDevice') else 'observational' if interface.endswith('Device8') else 'forward_only',
                'forwarding_status':'unchanged except documented COM pointer plumbing'})
        result[interface] = methods
    for method in result['IDirect3DDevice8']:
        if method['method'] in ('SetTextureStageState','SetTransform','GetTextureStageState','GetTransform','DrawPrimitive','DrawIndexedPrimitive'):
            method['forwarding_status']='default-off unchanged; documented R-GFX3/R-GFX4 gated override or logical getter virtualization'
        elif method['method'] in ('DrawPrimitiveUP','DrawIndexedPrimitiveUP'):
            method['forwarding_status']='unchanged except fail-closed repair after a reported native reflection restore failure'
        elif method['method'] in ('BeginStateBlock','ApplyStateBlock','CreateStateBlock','CaptureStateBlock','MultiplyTransform'):
            method['forwarding_status']='default-off unchanged; active visual state restored before unreviewed operation'
    if [len(result[x]) for x in result] != [16,97]:
        raise ValueError('Pinned header interface counts changed')
    return result

def generate():
    methods = interfaces((ROOT/'vendor/d3d8/d3d8.h').read_text())
    (ROOT/'data/interface-map.json').write_text(json.dumps({'schema_version':1,'source':'vendor/d3d8/d3d8.h','interfaces':methods},indent=2)+'\n',newline='\n')
    declarations = ['// Generated by tools/generate_interfaces.py. See pinned header provenance.',
        '#pragma once','#include "trace.hpp"','#include "game_fov.hpp"','#include <atomic>','#include <unordered_map>',
        'namespace gfx2 {','class Device8;',
        'class Root8 final : public IDirect3D8 {','public:',
        ' explicit Root8(IDirect3D8* p) : real_(p) {}',
        ' IDirect3D8* real() const noexcept { return real_; }',
        ' void adopt() noexcept { ++refs_; }',
        ' std::recursive_mutex registry_mutex;',
        ' std::unordered_map<IDirect3DDevice8*,Device8*> devices;']
    for m in methods['IDirect3D8']:
        declarations.append(f' __declspec(noinline) {m["return_type"]} STDMETHODCALLTYPE {m["method"]}({m["parameters"]}) override;')
    declarations += ['private: IDirect3D8* real_; std::atomic<ULONG> refs_{1};','};',
        'class Device8 final : public IDirect3DDevice8 {','public:',
        ' Device8(IDirect3DDevice8* p, Root8* parent) noexcept;',
        ' ~Device8();',
        ' void adopt() noexcept { ++refs_; }',' Trace trace;',' VisualPolicy visuals;',' GameFov game_fov;',' HRESULT stock_for_unmapped(const char* reason) noexcept;',' HRESULT repair_reflection() noexcept;',' HRESULT draw_indexed_at(D3DPRIMITIVETYPE type,UINT min_index,UINT vertices,UINT start,UINT count,uintptr_t pc);']
    for m in methods['IDirect3DDevice8']:
        declarations.append(f' __declspec(noinline) {m["return_type"]} STDMETHODCALLTYPE {m["method"]}({m["parameters"]}) override;')
    declarations += ['private: IDirect3DDevice8* real_; Root8* parent_; std::atomic<ULONG> refs_{1};','};','}']
    (ROOT/'include/wrappers.hpp').write_text('\n'.join(declarations)+'\n',newline='\n')
    lines = ['// Generated complete forwarders; COM plumbing is in wrappers.cpp.', '#include "wrappers.hpp"','#include <intrin.h>','namespace gfx2 {']
    names = []
    for interface, owner in [('IDirect3D8','Root8'),('IDirect3DDevice8','Device8')]:
        for m in methods[interface]:
            ret,name,params,args = m['return_type'],m['method'],m['parameters'],', '.join(m['arguments'])
            if name in ('QueryInterface','AddRef','Release','CreateDevice','GetDirect3D') or owner=='Device8' and name in ('SetTextureStageState','GetTextureStageState','SetTransform','GetTransform','DrawPrimitive','DrawIndexedPrimitive'):continue
            lines.append(f'{ret} STDMETHODCALLTYPE {owner}::{name}({params}) {{')
            if owner == 'Root8':
                lines.append(f' {"return " if ret!="void" else ""}real_->{name}({args});')
            else:
                lines += [' auto guard = trace.guard();',f' const auto args = pack({args});',f' const auto pc = reinterpret_cast<uintptr_t>(_ReturnAddress());',f' trace.before({m["slot"]}, args, pc);',
                    *([' trace.culling=game_fov.status(); game_fov.finish_frame(); trace.culling.restored=game_fov.status().restored;'] if name=='Present' else [' game_fov.finish_frame();'] if name=='Reset' else []),
                    *([f' HRESULT safe = stock_for_unmapped("{name}");', ' if(FAILED(safe)){ trace.after('+str(m['slot'])+', args, static_cast<uint32_t>(safe), pc); return safe; }'] if name in ('BeginStateBlock','ApplyStateBlock','CreateStateBlock','CaptureStateBlock') else [f' if(state==D3DTS_PROJECTION){{HRESULT safe=stock_for_unmapped("MultiplyTransform_PROJECTION");if(FAILED(safe)){{trace.after({m["slot"]},args,static_cast<uint32_t>(safe),pc);return safe;}}}}'] if name=='MultiplyTransform' else []),
                    *([' HRESULT repair=repair_reflection();',f' if(FAILED(repair)){{trace.after({m["slot"]},args,static_cast<uint32_t>(repair),pc,nullptr,8,true);return repair;}}'] if name in ('DrawPrimitiveUP','DrawIndexedPrimitiveUP') else []),
                    f' {ret+" result = " if ret!="void" else ""}real_->{name}({args});',
                    f' trace.after({m["slot"]}, args, {"static_cast<uint32_t>(result)" if ret!="void" else "0"}, pc);']
                if ret != 'void':lines.append(' return result;')
            lines.append('}')
    lines.append('}')
    (ROOT/'src/forwarders.cpp').write_text('\n'.join(lines)+'\n',newline='\n')
    names = [m['method'] for m in methods['IDirect3DDevice8']]
    (ROOT/'include/method_names.hpp').write_text('#pragma once\nnamespace gfx2 { inline constexpr const char* METHOD_NAMES[] = {\n'+',\n'.join(json.dumps(x) for x in names)+'\n}; }\n',newline='\n')
    mocks = ['// Generated ABI-wide mock methods and invocation tests.', '#pragma once', '#include "wrappers.hpp"', 'namespace gfx2 {']
    invokes = []
    for interface, owner in [('IDirect3D8','MockRootBase'),('IDirect3DDevice8','MockDeviceBase')]:
        mocks += [f'class {owner} : public {interface} {{', 'public:', ' uint32_t last=UINT32_MAX; Args observed{};', ' HRESULT hr=static_cast<HRESULT>(0x88761234u);']
        calls = []
        for m in methods[interface]:
            name, ret, params = m['method'], m['return_type'], m['parameters']
            body = f'last={m["slot"]};'
            if name != 'QueryInterface':body += 'observed=pack('+', '.join(m['arguments'])+');'
            body += 'return hr;' if ret == 'HRESULT' else 'return reinterpret_cast<HMONITOR>(0x12345678);' if ret == 'HMONITOR' else 'return 0x12345678;' if ret != 'void' else ''
            mocks.append(f' {ret} STDMETHODCALLTYPE {name}({params}) override {{ {body} }}')
            if name in ('QueryInterface','AddRef','Release','CreateDevice','GetDirect3D'):continue
            args=[]
            for i,param in enumerate(params.split(',') if params else []):
                typ=re.sub(r'\s*\b\w+\s*$', '', param).strip()
                args.append(f'reinterpret_cast<{typ}>(uintptr_t({0x1000+i*16}))' if '*' in typ or typ in ('HWND','HMONITOR') else f'static_cast<{typ}>({i+1})')
            call=f'w->{name}('+', '.join(args)+')'
            calls += [' { m.last=UINT32_MAX;',f' {"auto result = " if ret != "void" else ""}{call};',f' CHECK(m.last=={m["slot"]});',
                      ' CHECK(m.observed.a==pack('+', '.join(args)+').a);']
            if ret!='void':calls.append(' CHECK(result=='+('m.hr' if ret=='HRESULT' else 'reinterpret_cast<HMONITOR>(0x12345678)' if ret=='HMONITOR' else '0x12345678')+');')
            calls.append(' }')
        mocks.append('};')
        invokes += [f'inline void test_all_{owner}({interface}* w, {owner}& m) {{']+calls+['}']
    (ROOT/'tests/mock_interfaces.hpp').write_text('\n'.join(mocks+invokes+['}'])+'\n',newline='\n')

if __name__ == '__main__':
    generate()
