#!/usr/bin/env python3
"""Regenerate a bounded, read-only Retail RaceTest marker-list inventory."""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY / "src"))

from master_rallye.course_xml import parse_course_xml  # noqa: E402


FAMILIES = (
    "StartArea",
    "FinishArea",
    "FinishAreaQuick",
    "RaceLine",
    "Cameras",
    "LeftInnerLimit",
    "LeftOuterLimit",
    "RightInnerLimit",
    "RightOuterLimit",
)


def inventory(data_root: Path) -> dict[str, dict]:
    inventory: dict[str, dict] = {
        name: {
            "courses": set(),
            "counts": Counter(),
            "total": 0,
            "positions": 0,
            "directions": 0,
        }
        for name in FAMILIES
    }
    sdk_inventory = json.loads(
        (REPOSITORY / "research" / "r5t_sdk1" / "retail-corpus-validation.json")
        .read_text(encoding="utf-8")
    )
    projects = sdk_inventory.get("course_projects", [])
    if len(projects) != 36:
        raise ValueError(f"expected the known 36-project Retail inventory, found {len(projects)}")
    for project in projects:
        xml_path = data_root / project["race_test_xml"]
        if not xml_path.is_file():
            raise FileNotFoundError(xml_path)
        document = parse_course_xml(xml_path)
        for marker_list in document.marker_lists:
            name = marker_list.name
            if name not in inventory:
                continue
            row = inventory[name]
            row["courses"].add(project["identity"])
            row["counts"][len(marker_list.markers)] += 1
            row["total"] += len(marker_list.markers)
            row["positions"] += sum(marker.position is not None for marker in marker_list.markers)
            row["directions"] += sum(marker.direction is not None for marker in marker_list.markers)
    return inventory


def _line_for(name: str, row: dict) -> str:
    counts = row["counts"]
    if counts:
        count_range = f"{min(counts)}–{max(counts)}"
        distribution = ", ".join(f"{count}: {courses}" for count, courses in sorted(counts.items()))
    else:
        count_range = "—"
        distribution = "absent"
    if name == "StartArea":
        status = "STRUCTURALLY_PRESENT; imported; BOUNDED_AUTHORING"
        semantic = "CONFIRMED_BY_RUNTIME_EDIT; authoring CONFIRMED_BY_RUNTIME_AUTHORING_TEST"
    elif name == "FinishArea":
        supported = counts.get(4, 0)
        status = (
            f"STRUCTURALLY_PRESENT; imported; BOUNDED_AUTHORING {supported}/36; "
            "other layouts IMPORTED_READ_ONLY"
        )
        semantic = "CONFIRMED_BY_RUNTIME_EDIT; authoring CONFIRMED_BY_RUNTIME_AUTHORING_TEST"
    elif name == "RaceLine":
        status = "STRUCTURALLY_PRESENT; bounded existing Marker Pos authoring; topology and Marker Dir read-only"
        semantic = "Marker Pos -> runtime progression CONFIRMED_BY_RUNTIME_EDIT; Marker Dir use UNKNOWN"
    elif name in {"LeftInnerLimit", "LeftOuterLimit", "RightInnerLimit", "RightOuterLimit"}:
        status = "STRUCTURALLY_PRESENT; bounded existing Marker Pos authoring; topology and Marker Dir read-only"
        if name == "LeftOuterLimit":
            semantic = "gaLimitsAI consumer CONFIRMED_BY_EXECUTABLE; local LimitState change CONFIRMED_BY_RUNTIME_STATE_DIFF"
        elif name == "LeftInnerLimit":
            semantic = "gaLimitsAI consumer CONFIRMED_BY_EXECUTABLE; direct runtime probe INCONCLUSIVE"
        else:
            semantic = "gaLimitsAI consumer CONFIRMED_BY_EXECUTABLE; individual runtime mutation not tested"
        semantic += "; geometric corridor correlation HIGH_CONFIDENCE, names not promoted to runtime roles"
    elif name == "Cameras":
        status = "STRUCTURALLY_PRESENT; IMPORTED_READ_ONLY position/direction diagnostics"
        semantic = "RaceTest list linkage to camera parameters UNKNOWN"
    else:
        status = "STRUCTURALLY_PRESENT; IMPORTED_READ_ONLY as generic Marker helpers"
        semantic = "RUNTIME_ROLE_UNKNOWN"
    return (
        f"| `{name}` | {len(row['courses'])}/36 | {row['total']} ({count_range}) | {distribution} | "
        f"Marker Pos {row['positions']}; Marker Dir {row['directions']} | "
        f"{status} | {semantic} |"
    )


def render(rows: dict[str, dict]) -> str:
    lines = [
        "# Course marker-list backlog",
        "",
        "Read-only inventory of selected MarkerLists in the 36 principal Retail course RaceTest XML files.",
        "Generated by `python tools/scanner/course_marker_backlog.py`. Counts describe parsed source structure; names alone do not establish runtime semantics.",
        "",
        "Every observed marker in these lists has a parsed `Marker Pos` and `Marker Dir` value. The add-on preserves source record metadata. G1.1 permits edits only to existing `Marker Pos` XYZ in RaceLine and the four literal limit lists; list membership/order and Marker Dir remain read-only. StartArea/FinishArea retain their existing bounded workflow. Cameras remain read-only.",
        "",
        "SplitTime procedural sign cards and local-basis direction rays are placed at the visual-companion Eggs and use each companion's own matrix. RaceLine and limit marker helpers retain source order; moving a point updates its read-only diagnostic polyline. Marker Dir remains a preview, not an authored field.",
        "",
        "| Source list name | Course coverage | Markers total (per-course range) | Marker count distribution (markers/course: courses) | Parsed fields | Current import status | Semantic evidence |",
        "|---|---:|---:|---|---|---|---|",
    ]
    lines.extend(_line_for(name, rows[name]) for name in FAMILIES)
    lines.extend([
        "",
        "## Evidence boundary",
        "",
        "- `StartArea`: runtime edits confirm that its four ordered marker positions define the physical starting-grid frame; exact slot interpolation is unknown.",
        "- `FinishArea`: runtime edits confirm that its marker geometry affects the race-completion region; it is not claimed to be the sole finish subsystem.",
        "- `RaceLine Marker Pos` influences runtime progression. No AI-steering change was observed in the one local probe; AI use is not ruled out globally.",
        "- All four exact limit lists feed `gaLimitsAI` and produce `LimitState`. LeftOuterLimit[58..60] changed the local state in one runtime comparison; LeftInnerLimit[98..100] was inconclusive; the right-side lists have no individual runtime mutation result.",
        "- Limit positions correlate geometrically with an ordered route/corridor. This is not proof that list names literally mean road edges, reset boundaries, or collision boundaries.",
        "- `Cameras` is structurally present and imported read-only; its XML-to-camera-system link and runtime behavior remain unknown.",
        "- `FinishAreaQuick` is one additional literal list name observed in the principal corpus. Its name is not treated as semantic proof.",
        "- G1.1 authoring changes only pre-existing Marker Pos XYZ on RaceLine and the four limit lists. Marker direction and all other source fields remain preserved.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data-root",
        type=Path,
        default=REPOSITORY.parent / "corpora" / "retail" / "Data.sma_unpacked",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPOSITORY / "research" / "course_marker_backlog.md",
    )
    args = parser.parse_args()
    rows = inventory(args.data_root.expanduser().resolve())
    missing = [name for name, row in rows.items() if not row["courses"]]
    if missing:
        raise SystemExit(f"selected marker lists absent from the principal course corpus: {missing}")
    output = args.output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(rows), encoding="utf-8")
    print(f"wrote {output}; courses=36; lists={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
